import React from "react";
import Script from "next/script";
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Next.js Playground',
    description: 'Generated by create next app',
};

function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang={'en'}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* beforeInteractive: Loads BEFORE page hydration - must be in root layout */}
        <Script src={'/scripts/before-interactive.js'} strategy={'beforeInteractive'} id={'before-interactive-script'}/>
        {children}
        </body>
        </html>
    );
}

export default RootLayout;
