import React from "react";
import Script from "next/script";
import type {Metadata} from "next";
import {Roboto_Serif} from "next/font/google";
import "./globals.css";

const robotoSerif = Roboto_Serif({
    variable: '--font-roboto-serif',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Next.js Playground',
    description: 'Generated by create next app',
};

function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    // throw new Error('Root layout error!');

    return (
        <html lang={'en'}>
        <body className={`${robotoSerif.variable} antialiased`}>
        {/*
          beforeInteractive: Cookie Consent Banner
          This is a REAL third-party library (cookieconsent by orestbida)
          No account needed - completely free and open source
          Must load before page hydration so users see consent before any tracking
        */}
        <Script
            src={'https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.0.1/dist/cookieconsent.umd.js'}
            strategy={'beforeInteractive'}
            id={'cookie-consent-script'}
        />

        {/* Cookie Consent CSS */}
        <link rel={'stylesheet'} href="https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.0.1/dist/cookieconsent.css"/>

        {/* Initialize Cookie Consent after script loads */}
        <Script id={'cookie-consent-init'} strategy={'afterInteractive'}>
            {`
                if (typeof CookieConsent !== 'undefined') {
                    CookieConsent.run({
                        guiOptions: {
                            consentModal: {
                                layout: 'box',
                                position: 'bottom right'
                            }
                        },
                        categories: {
                            necessary: {
                                enabled: true,
                                readOnly: true
                            },
                            analytics: {
                                enabled: false,
                                readOnly: false
                            }
                        },
                        language: {
                            default: 'en',
                            translations: {
                                en: {
                                    consentModal: {
                                        title: 'We use cookies',
                                        description: 'This is a demo of beforeInteractive strategy. Cookie consent must load before any tracking scripts.',
                                        acceptAllBtn: 'Accept all',
                                        acceptNecessaryBtn: 'Reject all',
                                        showPreferencesBtn: 'Manage preferences'
                                    },
                                    preferencesModal: {
                                        title: 'Cookie preferences',
                                        acceptAllBtn: 'Accept all',
                                        acceptNecessaryBtn: 'Reject all',
                                        savePreferencesBtn: 'Save preferences',
                                        sections: [
                                            {
                                                title: 'Necessary cookies',
                                                description: 'These cookies are essential for the website to function.',
                                                linkedCategory: 'necessary'
                                            },
                                            {
                                                title: 'Analytics cookies',
                                                description: 'These cookies help us understand how visitors use the website.',
                                                linkedCategory: 'analytics'
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    });
                    console.log('[COOKIE CONSENT] Initialized successfully');
                }
            `}
        </Script>

        {children}
        </body>
        </html>
    );
}

export default RootLayout;
